- ros_topic_name: lidar3d_0/scan
  gz_topic_name: /a200_0000/sensors/lidar3d_0/scan
  ros_type_name: sensor_msgs/msg/LaserScan
  gz_type_name: gz.msgs.LaserScan
  direction: GZ_TO_ROS
- ros_topic_name: lidar3d_0/points
  gz_topic_name: /a200_0000/sensors/lidar3d_0/scan/points
  ros_type_name: sensor_msgs/msg/PointCloud2
  gz_type_name: gz.msgs.PointCloudPacked
  direction: GZ_TO_ROS
